# Generated by Django 5.0.7 on 2024-07-28 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_user_username_user_groups_user_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tipo',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('REGISTRO', 'REGISTRO'), ('CONSULTA', 'CONSULTA')], db_column='tipo', default='ADMIN', max_length=50),
        ),
    ]
